# Generated by Django 5.2.13 on 2026-04-29 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_educativo', models.CharField(max_length=200)),
                ('codigo_centro', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('grado_seccion', models.CharField(max_length=50)),
                ('centro_educativo', models.CharField(blank=True, max_length=200)),
                ('materia', models.CharField(choices=[('matematica', 'Números y Formas'), ('lenguaje', 'Comunicación'), ('ciencias', 'Ciencia y Tecnología'), ('sociales', 'Ciudadanía y Valores'), ('ingles', 'Inglés'), ('artistica', 'Expresión Artística'), ('otra', 'Otra')], max_length=20)),
                ('materia_otra', models.CharField(blank=True, max_length=50)),
                ('tipo_actividad', models.CharField(choices=[('explicacion', 'Explicación oral'), ('individual', 'Trabajo individual'), ('grupal', 'Trabajo grupal'), ('evaluacion', 'Evaluación formativa'), ('practica', 'Actividad práctica')], max_length=20)),
                ('momento', models.CharField(choices=[('inicio', 'Inicio'), ('desarrollo', 'Desarrollo'), ('cierre', 'Cierre')], max_length=20)),
                ('nivel_registro', models.CharField(choices=[('individual', 'Estudiante individual'), ('grupo', 'Grupo completo'), ('subgrupo', 'Subgrupo')], max_length=20)),
                ('codigo_estudiante', models.CharField(blank=True, max_length=10)),
                ('atencion', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('instrucciones', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('autorregulacion', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('participacion', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('interaccion_social', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('evento_puntual', models.CharField(blank=True, choices=[('conducta', 'Cambio abrupto de conducta'), ('conflicto', 'Conflicto con compañero'), ('abandono', 'Abandono de tarea'), ('ruido', 'Ruido ambiental intenso'), ('recurso', 'Falta de material didáctico'), ('otro', 'Otro')], max_length=20)),
                ('evento_otro', models.CharField(blank=True, max_length=60)),
                ('observacion_breve', models.CharField(blank=True, max_length=60)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro MaIA',
                'verbose_name_plural': 'Registros MaIA',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_anonimo', models.CharField(max_length=10)),
                ('grado_seccion', models.CharField(max_length=50)),
                ('distintivo', models.CharField(blank=True, help_text="Rasgo observable (ej: 'camiseta rayada', 'usa lentes')", max_length=100)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('docente', 'codigo_anonimo')},
            },
        ),
    ]
